### ISSUE TITLE
Conditional queries

### ISSUE THREAD

**Issue by duarteguilherme** [sachsmc/causaloptim#2]
I am interested in deriving bounds for a query with selection bias. In my case, D -> M -> Y, D -> Y, Ur -> M, Ur -> Y. 
Given this setting, P(Y(D = 1)|M = 1) - P(Y(D = 0)|M = 1) is a non-identifiable quantity. This is a counterfactual query, as M = 1 belongs to the world that we did not fix the value of D.

I wonder if there is a way of writing this query using causal optim package. I tried deriving bounds for "p{Y(D = 1) = 1; M = 1} - p{Y(D = 0) = 1; M = 1}" and then , "p{M = 1}", but in this case there is no guarantee that my bounds will be tight.

 
Here is the code I am using.

```
library(causaloptim)

b <- graph_from_literal(M -+ Y, D -+ M, D -+ Y, Ur -+ M, Ur -+ Y)
V(b)$latent <- c(0,0,0,1)
V(b)$leftside <- c(0,0,1,0)
E(b)$rlconnect <- c(0,0,0,0,0)
E(b)$edge.monotone <- c(0,0,0,0,0)


# plot(b)

obj <- analyze_graph(b, constraints = NULL, effectt = "p{Y(D = 1) = 1; M = 1} - p{Y(D = 0) = 1; M = 1}")
optimize_effect(obj)


obj2 <- analyze_graph(b, constraints = NULL, effectt = "p{M = 1}")
optimize_effect(obj2)

```

**Comment by sachsmc** [comment]
Hi @duarteguilherme , 

Unfortunately the answer is no. We do not allow for specifying conditional quantities such as the one you wrote, because as I think you understand, this makes the causal objective a nonlinear quantity. In that case this method does not apply, and the bounds may not be tight though you can potentially use it to get valid bounds. Some other method would need to be used, but I'm afraid I'm not aware of a general purpose one that applies. 

Best wishes,

Michael

**Comment by duarteguilherme** [comment]
That's what I imagined. Thank you so much.

**Comment by sachsmc** [comment]
I'm going to close this issue now, but feel free to ask any other questions that come up.
